import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  MIN_WORDS_PER_BAND,
  assertBandFloor,
  countByBand,
  deriveWords,
  readPinnedDigest,
  readSource,
  renderModule,
} from '../../../scripts/build-anagram-index'

// A scratch directory outside the repo, for the digest rows: nothing is written in the work tree.
const scratch = mkdtempSync(join(tmpdir(), 'anagram-index-'))
const sourcePath = join(scratch, 'enable.txt')
const digestPath = join(scratch, 'enable.sha256')

// One entry, so the digest below is independently checkable rather than computed by the code under
// test.
const SCRATCH_SOURCE = 'abc\n'
const SCRATCH_DIGEST = 'edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb'

describe('build-anagram-index', () => {
  beforeAll(() => {
    writeFileSync(sourcePath, SCRATCH_SOURCE, 'utf8')
    writeFileSync(digestPath, `${SCRATCH_DIGEST}  enable.txt\n`, 'utf8')
  })

  afterAll(() => {
    rmSync(scratch, { force: true, recursive: true })
  })

  describe('deriveWords', () => {
    it('keeps an entry whose letters no other entry shares', () => {
      expect(deriveWords(['kettle', 'spatula', 'skillet'])).toStrictEqual(['kettle', 'skillet', 'spatula'])
    })

    it('drops both members of a class of two', () => {
      expect(deriveWords(['kettle', 'toaster', 'rotates'])).toStrictEqual(['kettle'])
    })

    // 'robot' is the row that pins the FLOOR at six rather than five. It is a real ENABLE entry with
    // no anagram partner, so it clears every other filter and only the window removes it.
    it('drops entries outside the 6-9 band and entries that are not a-z', () => {
      expect(deriveWords(['pot', 'robot', 'kettle', 'colanderish', 'saute-pan', 'CAFE'])).toStrictEqual(['kettle'])
    })

    it('returns the survivors sorted, so a regeneration is a reviewable diff', () => {
      expect(deriveWords(['spatula', 'kettle', 'ramekin'])).toStrictEqual(['kettle', 'ramekin', 'spatula'])
    })

    // The corpus here deliberately omits NIGGER: class-size-one proves no other ENABLE entry shares
    // GINGER's letters and says nothing about a charged word the corpus does not carry, so the
    // filter is BY KEY. Weakening step 3 to `chargedWords.has(word.toUpperCase())` reddens this row
    // alone, because every entry the key filter removes from the real corpus also IS a charged word.
    it('drops a word that anagrams to a charged word absent from the corpus', () => {
      expect(deriveWords(['ginger', 'kettle', 'ramekin'])).toStrictEqual(['kettle', 'ramekin'])
    })

    // A PLANTED class of two -- one charged word, one ordinary -- neither of which may survive.
    // Every filter applied BEFORE the grouping must be anagram-invariant, or it removes one member
    // of a class and leaves the other looking unique. Length and charset are; a blocklist read as
    // membership is not, and only a planted collision can tell the two orders apart.
    it('drops both members of a planted charged and ordinary class', () => {
      expect(deriveWords(['ginger', 'nigger', 'kettle'])).toStrictEqual(['kettle'])
    })

    // The other half of step 3, a strictly weaker statement than the key filter above.
    it('drops a charged word that no other entry anagrams to', () => {
      expect(deriveWords(['bollocks', 'ramekin'])).toStrictEqual(['ramekin'])
    })
  })

  describe('countByBand', () => {
    it('reports every band in the window, including an empty one', () => {
      expect(countByBand(['kettle', 'teapot', 'spatula'])).toStrictEqual({ 6: 2, 7: 1, 8: 0, 9: 0 })
    })
  })

  describe('assertBandFloor', () => {
    it('accepts counts at the floor', () => {
      expect(() =>
        assertBandFloor({
          6: MIN_WORDS_PER_BAND,
          7: MIN_WORDS_PER_BAND,
          8: MIN_WORDS_PER_BAND,
          9: MIN_WORDS_PER_BAND,
        }),
      ).not.toThrow()
    })

    // A floor that is not asserted is a floor nobody checks after the first run.
    it('throws naming the thin band', () => {
      expect(() => assertBandFloor({ 6: 12, 7: MIN_WORDS_PER_BAND, 8: MIN_WORDS_PER_BAND })).toThrow(
        'Band supply below 1000: {"6":12}',
      )
    })
  })

  describe('renderModule', () => {
    it('names its producer, its source and its license in the generated header', () => {
      const rendered = renderModule(['kettle'])

      expect(rendered).toContain('GENERATED by scripts/build-anagram-index.ts from scripts/data/enable.txt')
      expect(rendered).toContain('scripts/data/LICENSE-enable')
      expect(rendered).toContain('scripts/data/enable.sha256')
    })

    it('emits one quoted entry per line and a trailing newline', () => {
      expect(renderModule(['kettle', 'ramekin'])).toContain(
        "export const uniqueAnagramWords: string[] = [\n  'kettle',\n  'ramekin',\n]\n",
      )
    })
  })

  describe('readSource', () => {
    it('reads the pin from its own file rather than a script literal', () => {
      expect(readPinnedDigest(digestPath)).toEqual(SCRATCH_DIGEST)
    })

    it('returns the entries when the digest matches', () => {
      expect(readSource(sourcePath, digestPath)).toStrictEqual(['abc'])
    })

    // Throws, never warns and never continues: every claim downstream is a claim about one
    // specific list, and against a different one the output would still look like a word list.
    it('throws when the source does not match its pin', () => {
      const wrongDigestPath = join(scratch, 'wrong.sha256')
      writeFileSync(wrongDigestPath, `${'0'.repeat(64)}  enable.txt\n`, 'utf8')

      expect(() => readSource(sourcePath, wrongDigestPath)).toThrow('does not match its pin')
    })
  })
})
