import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime'
import Ajv from 'ajv'

import { Prompt, ToolSchema } from '../types'
import { log, logDebug } from '../utils/logging'

// Vendored from connections-api/src/services/bedrock.ts. Kept as close to that copy as the
// differing callers allow, so a fix in either repo is a readable diff against the other.
//
// SDK default is 3 attempts (exponential backoff, ~100-500ms base). Bumped to 4 for extra
// resilience against transient Bedrock throttling. The only caller of invokeModel is
// CreateCorpusFunction, which runs on a schedule under a 900s timeout, so the added
// inter-attempt backoff sleep is not a meaningful timeout risk.
//
// Nothing on the request path may ever reach this module. A Bedrock call cannot fit inside a
// request under any circumstances, which is why the corpus is generated by its own scheduled
// Lambda and merely READ by the generators.
const runtimeClient = new BedrockRuntimeClient({ maxAttempts: 4, region: 'us-east-1' })

// Standard JSON Schema mode, matching Anthropic's tool input_schema format — this lets one
// schema object drive both the tool definition sent to the model and the response validation below.
const ajv = new Ajv()

// corpusTool is a fixed, module-level schema object reused on every invocation, so cache the
// compiled validator per schema object rather than re-parsing the same JSON Schema on every call.
const validatorCache = new WeakMap<Record<string, any>, ReturnType<typeof ajv.compile>>()

const getValidator = (schema: Record<string, any>): ReturnType<typeof ajv.compile> => {
  const cached = validatorCache.get(schema)
  if (cached) {
    return cached
  }
  const validate = ajv.compile(schema)
  validatorCache.set(schema, validate)
  return validate
}

// Context values may originate from prior LLM output (e.g. category names), which is untrusted.
// Escaping </> stops it from breaking out of the <context> XML tags in the prompt templates.
const escapeXml = (value: string): string => value.replace(/</g, '&lt;').replace(/>/g, '&gt;')

// A replacer function (not a string) avoids Node interpreting $&/$`/$'-style sequences
// that might appear in untrusted context values as replacement patterns.
const buildPromptContents = (prompt: Prompt, context?: Record<string, any>): string =>
  context ? prompt.contents.replace('${context}', () => escapeXml(JSON.stringify(context))) : prompt.contents

const buildRequestBody = (prompt: Prompt, tool: ToolSchema, contents: string) => ({
  anthropic_version: prompt.config.anthropicVersion,
  max_tokens: prompt.config.maxTokens,
  messages: [{ content: contents, role: 'user' }],
  output_config: { effort: prompt.config.thinkingEffort },
  // Forced tool_choice ("tool"/"any") is not supported alongside extended thinking, so we can
  // only steer the model to call the tool via "auto" and validate that it did so below.
  thinking: { type: 'adaptive' },
  tool_choice: { type: 'auto' },
  tools: [tool],
})

const sendToBedrock = async (command: InvokeModelCommand, model: string) => {
  try {
    return await runtimeClient.send(command)
  } catch (error: unknown) {
    const err = error as {
      $metadata?: {
        attempts?: number
        httpStatusCode?: number
        requestId?: string
        totalRetryDelay?: number
      }
      message?: string
      name?: string
    } | null
    log('Bedrock invocation failed', {
      attempts: err?.$metadata?.attempts,
      errorName: err?.name,
      httpStatusCode: err?.$metadata?.httpStatusCode,
      message: err?.message,
      model,
      requestId: err?.$metadata?.requestId,
      totalRetryDelay: err?.$metadata?.totalRetryDelay,
    })
    throw error
  }
}

const decodeResponseBody = (body: Uint8Array | undefined, model: string) => {
  try {
    return JSON.parse(new TextDecoder().decode(body))
  } catch (error: unknown) {
    log('Failed to parse Bedrock response body as JSON', {
      message: (error as Error | null)?.message,
      model,
    })
    throw error
  }
}

const extractJson = (input: string): string => {
  const cleaned = input.replace(/(^\s*|\s*```(?:json)?\s*|\s*$)/gs, '')
  return cleaned.match(/{.*}/s)?.[0] ?? cleaned
}

// Thinking and the tool call share one max_tokens budget, so a run that spends the whole budget
// thinking returns no tool_use block at all. Logged on every invocation rather than only on failure:
// a failure count says nothing without knowing how much headroom a healthy game leaves, and that
// headroom is what tells us whether the effort level can come down.
const logModelUsage = (
  modelResponse: { stop_reason?: string; usage?: { input_tokens?: number; output_tokens?: number } },
  tool: ToolSchema,
  model: string,
): void => {
  log('Model invocation complete', {
    inputTokens: modelResponse.usage?.input_tokens,
    model,
    outputTokens: modelResponse.usage?.output_tokens,
    stopReason: modelResponse.stop_reason,
    toolName: tool.name,
  })
}

const extractModelPayload = (
  modelResponse: {
    content: { type: string; input?: unknown; name?: string; text?: string }[]
    stop_reason: string
  },
  tool: ToolSchema,
  model: string,
): unknown => {
  const toolUseBlock = modelResponse.content.find((b) => b.type === 'tool_use')
  if (toolUseBlock) {
    return toolUseBlock.input
  }

  const textBlock = modelResponse.content.find((b) => b.type === 'text')
  if (!textBlock?.text) {
    log('Model response missing tool_use block and text block', {
      blockTypes: modelResponse.content.map((b) => b.type),
      model,
      stopReason: modelResponse.stop_reason,
      toolName: tool.name,
    })
    throw new Error(`Model response contained no ${tool.name} tool call`)
  }

  log('Model replied without invoking the expected tool; falling back to text extraction', {
    model,
    toolName: tool.name,
  })
  try {
    return JSON.parse(extractJson(textBlock.text))
  } catch (error: unknown) {
    log('Failed to parse JSON from fallback text response', {
      message: (error as Error | null)?.message,
      model,
      textLength: textBlock.text.length,
    })
    throw error
  }
}

const VALIDATION_FAILURE_PREVIEW_LENGTH = 500

const validateResponse = <T>(tool: ToolSchema, parsed: unknown): T => {
  const validate = getValidator(tool.input_schema)
  if (!validate(parsed)) {
    const errors = ajv.errorsText(validate.errors)
    // Some payload detail here (unlike the routine per-invocation logs) is warranted since this is
    // the one moment the feature is meant to catch, and without it a validation failure is undebuggable.
    // Truncated at production log level since parsed may echo generated game/category content;
    // the untruncated payload is only ever logged when DEBUG_LOGGING is on.
    const preview = JSON.stringify(parsed).slice(0, VALIDATION_FAILURE_PREVIEW_LENGTH)
    log('Model response failed schema validation', {
      errors,
      parsedPreview: preview,
      toolName: tool.name,
    })
    logDebug('Model response failed schema validation (full payload)', {
      parsed,
      toolName: tool.name,
    })
    throw new Error(`Model response failed schema validation for tool "${tool.name}": ${errors}`)
  }
  return parsed as T
}

export const invokeModel = async <T>(prompt: Prompt, tool: ToolSchema, context?: Record<string, any>): Promise<T> => {
  const contents = buildPromptContents(prompt, context)
  logDebug('Invoking model', { contents, prompt, tool })

  const messageBody = buildRequestBody(prompt, tool, contents)
  log('Invoking model', { model: prompt.config.model, toolName: tool.name })

  const command = new InvokeModelCommand({
    body: new TextEncoder().encode(JSON.stringify(messageBody)),
    contentType: 'application/json',
    modelId: prompt.config.model,
  })

  const response = await sendToBedrock(command, prompt.config.model)
  const modelResponse = decodeResponseBody(response.body, prompt.config.model)
  // Before extraction, not after: extraction throws on the exact runs whose token counts matter most.
  logModelUsage(modelResponse, tool, prompt.config.model)
  const payload = extractModelPayload(modelResponse, tool, prompt.config.model)
  return validateResponse(tool, payload)
}
