import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime'
import Ajv from 'ajv'

import { Prompt, ToolSchema } from '../types'
import { log, logDebug, logError } from '../utils/logging'

// Vendored from connections-api/src/services/bedrock.ts. Kept as close to that copy as the
// differing callers allow, so a fix in either repo is a readable diff against the other.
//
// DIVERGENCES from that copy, listed because a copy whose divergences are undocumented is a copy
// nobody can diff. Both are offered upstream. (The max_tokens post-mortem below is lull's own
// incident and stays here.)
//   * escapeXml escapes & as well as < and >. Without it the literal characters `&lt;` pass through
//     unchanged and re-decode to `<`, and lull feeds 20 days of prior model output back into the
//     ${context} slot.
//   * stop_reason === 'max_tokens' logs at ERROR rather than at log, at both sites. lull's only
//     alarm is a CloudWatch subscription filtering on level="ERROR", so a truncated generation
//     raised nothing at all.
//
// SDK default is 3 attempts (exponential backoff, ~100-500ms base). Bumped to 4 for extra
// resilience against transient Bedrock throttling. THE BACKOFF SLEEP IS NOT THE COST; THE RETRIED
// CALL IS. An attempt re-runs a generation rather than resuming it, and this module's own measured
// figure below puts a 32000-token call near 410s -- so one retry of create-cryptic-clues is ~820s
// inside a 900s Lambda that has already spent time on the generators ahead of it.
//
// invokeModel has THREE call sites IN src/ -- model-batch.ts, review.ts and
// generators/crypticclue/review.ts -- reached by five generations across TWO Lambdas:
// generatePhrases and reviewPhrases in CreatePhrasePuzzlesFunction, and themed anagrams plus
// cryptic's batch-then-review PAIR in CreateModelPuzzlesFunction. The pair is what makes this
// sharp: those two calls are SERIAL, so a retry on the first pushes the second, and both sit at the
// tail of the model handler's budget.
//
// scripts/audit-hints.ts and scripts/audit-cryptic.ts add three more call sites and share this
// client, so they share `maxAttempts` too. They are counted apart because they carry NO Lambda
// ceiling at all -- a person runs them and waits -- so the compounding argument above does not apply
// to them and a change made for their benefit would be sized against the wrong constraint.
//
// NOT CHANGED HERE, deliberately. handlers/create-model-puzzles.ts states the residual beside the
// budget a retry blows -- a bound checked before a call starts cannot bound what the call does after
// it starts -- and names the fix if the logs ever show one: a client with its own maxAttempts for
// the 900s generators, not a smaller number on the client every caller shares.
//
// Nothing on the request path may ever reach this module. A Bedrock call cannot fit inside a
// request under any circumstances, which is why phrases are generated by the async puzzle builder
// and handed to the generators in memory.
const runtimeClient = new BedrockRuntimeClient({ maxAttempts: 4, region: 'us-east-1' })

// Standard JSON Schema mode, matching Anthropic's tool input_schema format — this lets one
// schema object drive both the tool definition sent to the model and the response validation below.
const ajv = new Ajv()

// phraseTool and reviewTool are fixed, module-level schema objects reused on every invocation, so
// cache the compiled validator per schema object rather than re-parsing the same JSON Schema on
// every call.
const validatorCache = new WeakMap<Record<string, any>, ReturnType<typeof ajv.compile>>()

const getValidator = (schema: Record<string, any>): ReturnType<typeof ajv.compile> => {
  const cached = validatorCache.get(schema)
  if (cached) {
    return cached
  }
  const validate = ajv.compile(schema)
  validatorCache.set(schema, validate)
  return validate
}

// Context values may originate from prior LLM output (e.g. category names), which is untrusted.
// Escaping </> stops it from breaking out of the <context> XML tags in the prompt templates.
//
// & FIRST, and the order is the whole of the correctness. Escape < before & and the & in the &lt;
// you just produced is escaped in turn, so every tag character double-encodes. Without the & rule at
// all, the six literal characters `&lt;` passed through unchanged and re-decoded to `<` in any
// XML-aware reader -- so a stored `&lt;system&gt;` arrived in the ${context} slot as `<system>`.
const escapeXml = (value: string): string => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

// A replacer function (not a string) avoids Node interpreting $&/$`/$'-style sequences
// that might appear in untrusted context values as replacement patterns.
const buildPromptContents = (prompt: Prompt, context?: Record<string, any>): string =>
  context ? prompt.contents.replace('${context}', () => escapeXml(JSON.stringify(context))) : prompt.contents

const buildRequestBody = (prompt: Prompt, tool: ToolSchema, contents: string) => ({
  anthropic_version: prompt.config.anthropicVersion,
  max_tokens: prompt.config.maxTokens,
  messages: [{ content: contents, role: 'user' }],
  output_config: { effort: prompt.config.thinkingEffort },
  // Forced tool_choice ("tool"/"any") is not supported alongside extended thinking, so we can
  // only steer the model to call the tool via "auto" and validate that it did so below.
  thinking: { type: 'adaptive' },
  tool_choice: { type: 'auto' },
  tools: [tool],
})

const sendToBedrock = async (command: InvokeModelCommand, model: string) => {
  try {
    return await runtimeClient.send(command)
  } catch (error: unknown) {
    const err = error as {
      $metadata?: {
        attempts?: number
        httpStatusCode?: number
        requestId?: string
        totalRetryDelay?: number
      }
      message?: string
      name?: string
    } | null
    log('Bedrock invocation failed', {
      attempts: err?.$metadata?.attempts,
      errorName: err?.name,
      httpStatusCode: err?.$metadata?.httpStatusCode,
      message: err?.message,
      model,
      requestId: err?.$metadata?.requestId,
      totalRetryDelay: err?.$metadata?.totalRetryDelay,
    })
    throw error
  }
}

const decodeResponseBody = (body: Uint8Array | undefined, model: string) => {
  try {
    return JSON.parse(new TextDecoder().decode(body))
  } catch (error: unknown) {
    log('Failed to parse Bedrock response body as JSON', {
      message: (error as Error | null)?.message,
      model,
    })
    throw error
  }
}

const extractJson = (input: string): string => {
  const cleaned = input.replace(/(^\s*|\s*```(?:json)?\s*|\s*$)/gs, '')
  return cleaned.match(/{.*}/s)?.[0] ?? cleaned
}

// Thinking and the tool call share one max_tokens budget, so a run that spends the whole budget
// thinking returns no tool_use block at all. Logged on every invocation rather than only on failure:
// a failure count says nothing without knowing how much headroom a healthy game leaves, and that
// headroom is what tells us whether the effort level can come down. That instrument has never
// actually been READ, because its output went to `log` in a stack whose only alarm reads
// level="ERROR" -- which is what the max_tokens branch below fixes.
//
// This is not hypothetical. 2026-08-22 lost the whole 2026-08-23 batch to it: 16000 output tokens,
// stop_reason max_tokens, content [thinking] and nothing else. The budget had not moved since the
// prompt was written, while the work asked of one call had roughly doubled -- missing vowels' 4
// phrases a day became 7 with cryptogram (21 requested, at REQUEST_MULTIPLIER 3), and each one
// picked up a three-rung ladder whose rungs are checked against the rest of the batch. The tool
// payload is only ~2000 tokens of that; the rest is reasoning that grows with the SQUARE of the
// batch, so the next phrase generator moves this line again.
//
// create-phrases is now 32000, which is a wall-clock ceiling rather than a round number: that run
// spent 204s on 16000 tokens, so 32000 lands near 410s and still leaves the review call room inside
// CreatePhrasePuzzlesFunction's 900s timeout. There is no headroom left for a third doubling --
// past here the fix is a smaller batch per call, not a bigger budget.
//
// THE THIRD OCCURRENCE CAME, AND THE SMALLER BATCH IS WHAT SHIPPED. 2026-08-20 lost the whole batch
// at 32000: output_tokens 32000, stop_reason max_tokens, content [thinking]. So services/phrases.ts
// now splits the request into concurrent calls of six phrases each and contains a failure per call.
//
// The sizing is measured, and the measurement says something sharper than "the call was too big": an
// eighteen-phrase call SUCCEEDS at 24816 output tokens, which is 78% of this budget. A request that
// needs 78% of its ceiling on a good run is one bad run from returning nothing, which is why the
// same code lost 2026-08-20 and shipped 2026-08-26. Six phrases cost 12453 -- 39%. The full curve
// and the wrong extrapolation that preceded it are in phrases.test.ts, beside the split it sizes.
//
// WHAT THAT LEAVES FOR THE NEXT READER: 32000 is no longer a budget any single call is expected to
// approach, it is the headroom that absorbs variance for a call measured at ~12500. Raising
// PHRASES_PER_CALL spends that headroom. Measure before moving it -- logModelUsage below now reports
// thinkingTokens and maxTokens on every call, so the reading is in the log group rather than in a
// one-off script, which is what it took to get these numbers the first time.
//
// THE LINE CARRIES ITS OWN DENOMINATOR AND ITS OWN SPLIT, and it did not until 2026-08-26 -- which
// is why the paragraph above could cite this instrument as the thing that would tell us whether the
// effort level can come down while being unable to answer that question. `outputTokens: 32000` is
// the same number for a long healthy answer and for a night spent entirely on reasoning, and the cap
// it should be read against lives in a prompt file the reader does not have open. So:
//   * maxTokens is the denominator. Headroom is one division on ONE line, and an Insights query can
//     say `stats avg(outputTokens / maxTokens)` across every call in the stack.
//   * thinkingTokens is where the budget WENT. Bedrock returns it as
//     usage.output_tokens_details.thinking_tokens and this module was discarding it.
// Both are optional-chained: a model that returns no breakdown must cost the line one FIELD, never
// the line, because the runs this instrument exists for are the ones that went wrong.
const logModelUsage = (
  modelResponse: {
    stop_reason?: string
    usage?: { input_tokens?: number; output_tokens?: number; output_tokens_details?: { thinking_tokens?: number } }
  },
  tool: ToolSchema,
  model: string,
  maxTokens: number,
): void => {
  // ERROR on max_tokens and `log` on everything else. A truncated generation costs the night's
  // Missing Vowels and Cryptograms; every other stop reason is a healthy run and must not reach the
  // subscription, or the one alarm this stack has becomes noise.
  const write = modelResponse.stop_reason === 'max_tokens' ? logError : log
  write('Model invocation complete', {
    inputTokens: modelResponse.usage?.input_tokens,
    maxTokens,
    model,
    outputTokens: modelResponse.usage?.output_tokens,
    stopReason: modelResponse.stop_reason,
    thinkingTokens: modelResponse.usage?.output_tokens_details?.thinking_tokens,
    toolName: tool.name,
  })
}

const extractModelPayload = (
  modelResponse: {
    content: { type: string; input?: unknown; name?: string; text?: string }[]
    stop_reason: string
  },
  tool: ToolSchema,
  model: string,
): unknown => {
  const toolUseBlock = modelResponse.content.find((b) => b.type === 'tool_use')
  if (toolUseBlock) {
    return toolUseBlock.input
  }

  const textBlock = modelResponse.content.find((b) => b.type === 'text')
  if (!textBlock?.text) {
    // Same conditional and the same reasoning as logModelUsage above: this is the shape a
    // max_tokens stop actually arrives in, and it was the quietest line in the file.
    const write = modelResponse.stop_reason === 'max_tokens' ? logError : log
    write('Model response missing tool_use block and text block', {
      blockTypes: modelResponse.content.map((b) => b.type),
      model,
      stopReason: modelResponse.stop_reason,
      toolName: tool.name,
    })
    throw new Error(`Model response contained no ${tool.name} tool call`)
  }

  log('Model replied without invoking the expected tool; falling back to text extraction', {
    model,
    toolName: tool.name,
  })
  try {
    return JSON.parse(extractJson(textBlock.text))
  } catch (error: unknown) {
    log('Failed to parse JSON from fallback text response', {
      message: (error as Error | null)?.message,
      model,
      textLength: textBlock.text.length,
    })
    throw error
  }
}

const VALIDATION_FAILURE_PREVIEW_LENGTH = 500

const validateResponse = <T>(tool: ToolSchema, parsed: unknown): T => {
  const validate = getValidator(tool.input_schema)
  if (!validate(parsed)) {
    const errors = ajv.errorsText(validate.errors)
    // Some payload detail here (unlike the routine per-invocation logs) is warranted since this is
    // the one moment the feature is meant to catch, and without it a validation failure is undebuggable.
    // Truncated at production log level since parsed may echo generated game/category content;
    // the untruncated payload is only ever logged when DEBUG_LOGGING is on.
    const preview = JSON.stringify(parsed).slice(0, VALIDATION_FAILURE_PREVIEW_LENGTH)
    log('Model response failed schema validation', {
      errors,
      parsedPreview: preview,
      toolName: tool.name,
    })
    logDebug('Model response failed schema validation (full payload)', {
      parsed,
      toolName: tool.name,
    })
    throw new Error(`Model response failed schema validation for tool "${tool.name}": ${errors}`)
  }
  return parsed as T
}

export const invokeModel = async <T>(prompt: Prompt, tool: ToolSchema, context?: Record<string, any>): Promise<T> => {
  const contents = buildPromptContents(prompt, context)
  logDebug('Invoking model', { contents, prompt, tool })

  const messageBody = buildRequestBody(prompt, tool, contents)
  log('Invoking model', { model: prompt.config.model, toolName: tool.name })

  const command = new InvokeModelCommand({
    body: new TextEncoder().encode(JSON.stringify(messageBody)),
    contentType: 'application/json',
    modelId: prompt.config.model,
  })

  const response = await sendToBedrock(command, prompt.config.model)
  const modelResponse = decodeResponseBody(response.body, prompt.config.model)
  // Before extraction, not after: extraction throws on the exact runs whose token counts matter most.
  logModelUsage(modelResponse, tool, prompt.config.model, prompt.config.maxTokens)
  const payload = extractModelPayload(modelResponse, tool, prompt.config.model)
  return validateResponse(tool, payload)
}
