import { readFileSync } from 'fs'
import { join } from 'path'

import { DATA_FILE, SPECS, parseEntries, renderFile, selectFor } from '../../../scripts/build-word-lists'
import { excludedSeeds } from '../../../scripts/excluded-seeds'
import { adjectives } from '../../../src/assets/adjectives'
import { chargedWords } from '../../../src/assets/blocklist'
import { nouns } from '../../../src/assets/nouns'
import { verbs } from '../../../src/assets/verbs'

// These lists are generated by scripts/build-word-lists.ts. The previous hand-assembled lists
// overlapped in 307 places, carried abbreviations like "p" and "tv", and held lowercased proper
// nouns, and nothing caught any of it.
describe('word lists', () => {
  const byName: Record<string, string[]> = { adjectives, nouns, verbs }
  const lists: [string, string[]][] = SPECS.map((spec) => [spec.name, byName[spec.name]])

  const overlap = (left: string[], right: string[]): string[] => {
    const rightSet = new Set(right)
    return left.filter((word) => rightSet.has(word))
  }

  // The strongest assertion available, and the one that subsumes caps, sorting, filtering, and
  // exclusions: regenerate from the vendored dataset and compare to what is committed. Without it
  // nothing connects the asset files to the script, and a hand edit would go unnoticed forever --
  // which matters, because the generated header tells readers not to hand-edit.
  describe('reproducibility', () => {
    const contents = readFileSync(DATA_FILE, 'utf-8')
    const entries = parseEntries(contents)
    const vocabulary = new Set(entries.map((entry) => entry.word))
    const partOfSpeech = new Map(entries.map((entry) => [entry.word, entry.partOfSpeech]))

    it.each(SPECS.map((spec) => [spec.name, spec] as const))('regenerates %s byte for byte', (name, spec) => {
      const rendered = renderFile(name, selectFor(entries, spec, vocabulary, partOfSpeech))
      expect(rendered).toEqual(readFileSync(join(__dirname, '..', '..', '..', 'src', 'assets', `${name}.ts`), 'utf-8'))
    })
  })

  describe('structure', () => {
    it.each([
      ['nouns', 'verbs', nouns, verbs],
      ['nouns', 'adjectives', nouns, adjectives],
      ['verbs', 'adjectives', verbs, adjectives],
    ])('shares no words between %s and %s', (_left, _right, left, right) => {
      expect(overlap(left, right)).toEqual([])
    })

    it.each(lists)('has no duplicates within %s', (_name, list) => {
      expect(list.length - new Set(list).size).toEqual(0)
    })

    // Lowercase letters only. NOTE: this does not keep proper nouns out -- the source dataset is
    // entirely lowercase, so there is no capitalization left to test. excludedSeeds does that job.
    it.each(lists)('contains only lowercase words of 3 to 12 letters in %s', (_name, list) => {
      expect(list.filter((word) => !/^[a-z]{3,12}$/.test(word))).toEqual([])
    })

    it.each(lists)('is sorted alphabetically in %s', (_name, list) => {
      expect(list).toEqual(list.toSorted())
    })

    /*
     * Derived from SPECS rather than restated, so the numbers cannot drift between script and test.
     *
     * THE FLOOR, NOT THE CAP, and the two stopped being the same number on 2026-09-05. This asserted
     * `toHaveLength(spec.cap)` back when every pool overflowed its cap, so the list length WAS the
     * cap and the assertion read as exact. The lists now take everything the filters admit -- the
     * cap was throwing away 1193 nouns of identical quality -- so an exact length would have to be
     * updated by hand every time a word joins excluded-seeds.ts, which is a test that fails for
     * being right.
     *
     * The floor is what the check was always FOR: scripts/data/README.md documents a CRLF footgun
     * that makes all three lists come out empty, and an empty list feeds [undefined x 10] into the
     * model context rather than failing anything.
     */
    it.each(SPECS.map((spec) => [spec.name, byName[spec.name], spec.floor] as const))(
      'holds at least the %s floor',
      (_name, list, floor) => {
        expect(list.length).toBeGreaterThanOrEqual(floor)
      },
    )
  })

  describe('exclusions', () => {
    it.each(lists)('contains no charged terms in %s', (_name, list) => {
      expect(list.filter((word) => chargedWords.has(word.toUpperCase()))).toEqual([])
    })

    // excludedSeeds is an open-ended denylist against classes no ranking signal separates. Without
    // this assertion it is a comment rather than a guarantee.
    it.each(lists)('contains no excluded seeds in %s', (_name, list) => {
      expect(list.filter((word) => excludedSeeds.has(word))).toEqual([])
    })

    // Regression cases, one per category. Every one shipped at some point and was caught by review
    // rather than by a test. Named individually so a failure says which class leaked.
    it.each([
      ['demonym', 'pygmy'],
      ['lowercased proper noun', 'bible'],
      ['sexual anatomy', 'clitoris'],
      ['blocklist-evading compound', 'whorehouse'],
      ['excretion', 'urinate'],
      ['undress', 'topless'],
      ['drug', 'heroin'],
      ['crude', 'cock'],
      ['graphic violence', 'mutilate'],
      ['demeaning', 'obese'],
    ])('excludes the %s "%s"', (_category, word) => {
      expect([...nouns, ...verbs, ...adjectives]).not.toContain(word)
    })

    // Named rather than left to the reproducibility row, because this one is a PRODUCT decision and
    // a failure here should say so: these lists are displayed, not just prompted with, so GREY was a
    // word the game asked a player to spell. `greyhound` is in the same assertion because the
    // obvious way to implement the exclusion -- a find-and-replace over "grey" -- breaks it.
    it('ships the American spelling and keeps greyhound', () => {
      expect(adjectives).toContain('gray')
      expect(adjectives).not.toContain('grey')
      expect(nouns).toContain('greyhound')
    })
  })

  describe('content', () => {
    it('keeps concrete, imageable nouns', () => {
      expect(nouns).toEqual(expect.arrayContaining(['accordion', 'alligator', 'blowtorch', 'stepladder']))
    })

    it('drops the abstract heads of a frequency-ranked list', () => {
      const abstract = ['way', 'thing', 'case', 'part', 'point', 'fact', 'time', 'year', 'people']
      expect(overlap([...nouns, ...verbs, ...adjectives], abstract)).toEqual([])
    })

    // Dom_Pos mislabels concrete nouns as verbs, and ranking by concreteness selects for the error.
    // stat/rang/slid are the subtler half: each matched an -ed or -ing form belonging to a longer
    // lemma (state, range, slide).
    it('keeps mislabeled nouns and truncations out of the verb list', () => {
      const mislabeled = ['absinthe', 'clamshell', 'cornflake', 'escargot', 'rang', 'slid', 'stat']
      expect(overlap(verbs, mislabeled)).toEqual([])
    })

    // Compound nouns are not inflections. An earlier revision recovered a "base" by blindly
    // stripping four characters from anything ending in -ing, which read "earring" as ear+ring.
    it('keeps compound nouns that merely end in an inflection-like suffix', () => {
      expect(nouns).toEqual(expect.arrayContaining(['earring', 'riverbed', 'seedling', 'woodshed']))
    })

    // Plurals are always waste: dog/dogs spend two of a draw's ten slots on one idea. Checked
    // across every list. An earlier version of this test looked only at -ing verbs, where the sole
    // candidates were cling, sing, and swing -- so it could not fail.
    it.each(lists)('keeps a word and its own plural out of %s', (_name, list) => {
      const present = new Set(list)
      const pairs = list.filter((word) =>
        [word.replace(/es$/, ''), word.replace(/s$/, '')].some(
          (base) => base !== word && base.length > 2 && present.has(base),
        ),
      )
      expect(pairs).toEqual([])
    })

    // -ing and -ed forms are NOT treated as duplicates unless their base is a verb, and that
    // asymmetry is deliberate. bowling, icing, railing, and barefooted are nominalizations and
    // participles that name their own things -- distinct seeds from bowl, ice, rail, and barefoot,
    // and worth keeping. Only blink/blinked, where the base really is a verb, is waste.
    it('keeps nominalizations whose base is a noun', () => {
      expect(nouns).toEqual(expect.arrayContaining(['bowling', 'icing', 'railing']))
    })

    it('drops an -ed or -ing form whose base is a verb in the same list', () => {
      const present = new Set(verbs)
      const pairs = verbs.filter((word) =>
        [word.replace(/ing$/, ''), word.replace(/ing$/, 'e'), word.replace(/ed$/, ''), word.replace(/ed$/, 'e')].some(
          (base) => base !== word && base.length > 2 && present.has(base),
        ),
      )
      expect(pairs).toEqual([])
    })
  })
})
