import { readFileSync } from 'fs'
import { join } from 'path'

import { DATA_FILE, SPECS, parseEntries, renderFile, selectFor } from '../../../scripts/build-word-lists'
import { excludedSeeds } from '../../../scripts/excluded-seeds'
import { adjectives } from '../../../src/assets/adjectives'
import { chargedWords } from '../../../src/assets/blocklist'
import { nouns } from '../../../src/assets/nouns'
import { verbs } from '../../../src/assets/verbs'

// These lists are generated by scripts/build-word-lists.ts and must not be hand-edited.
describe('word lists', () => {
  const byName: Record<string, string[]> = { adjectives, nouns, verbs }
  const lists: [string, string[]][] = SPECS.map((spec) => [spec.name, byName[spec.name]])

  const overlap = (left: string[], right: string[]): string[] => {
    const rightSet = new Set(right)
    return left.filter((word) => rightSet.has(word))
  }

  // Subsumes caps, sorting, filtering and exclusions, and is the only thing connecting the assets
  // to the script that generates them.
  describe('reproducibility', () => {
    const contents = readFileSync(DATA_FILE, 'utf-8')
    const entries = parseEntries(contents)
    const vocabulary = new Set(entries.map((entry) => entry.word))
    const partOfSpeech = new Map(entries.map((entry) => [entry.word, entry.partOfSpeech]))

    it.each(SPECS.map((spec) => [spec.name, spec] as const))('regenerates %s byte for byte', (name, spec) => {
      const rendered = renderFile(name, selectFor(entries, spec, vocabulary, partOfSpeech))
      expect(rendered).toEqual(readFileSync(join(__dirname, '..', '..', '..', 'src', 'assets', `${name}.ts`), 'utf-8'))
    })
  })

  describe('structure', () => {
    it.each([
      ['nouns', 'verbs', nouns, verbs],
      ['nouns', 'adjectives', nouns, adjectives],
      ['verbs', 'adjectives', verbs, adjectives],
    ])('shares no words between %s and %s', (_left, _right, left, right) => {
      expect(overlap(left, right)).toEqual([])
    })

    it.each(lists)('has no duplicates within %s', (_name, list) => {
      expect(list.length - new Set(list).size).toEqual(0)
    })

    // This does not keep proper nouns out: the source dataset is lowercase, so excludedSeeds does.
    it.each(lists)('contains only lowercase words of 3 to 12 letters in %s', (_name, list) => {
      expect(list.filter((word) => !/^[a-z]{3,12}$/.test(word))).toEqual([])
    })

    it.each(lists)('is sorted alphabetically in %s', (_name, list) => {
      expect(list).toEqual(list.toSorted())
    })

    // Derived from SPECS, so the numbers cannot drift between script and test, and a floor rather
    // than an exact length because the lists take everything the filters admit. scripts/data has a
    // CRLF footgun that empties all three, and an empty list feeds [undefined x 10] to the model.
    it.each(SPECS.map((spec) => [spec.name, byName[spec.name], spec.floor] as const))(
      'holds at least the %s floor',
      (_name, list, floor) => {
        expect(list.length).toBeGreaterThanOrEqual(floor)
      },
    )
  })

  describe('exclusions', () => {
    it.each(lists)('contains no charged terms in %s', (_name, list) => {
      expect(list.filter((word) => chargedWords.has(word.toUpperCase()))).toEqual([])
    })

    // excludedSeeds is an open-ended denylist against classes no ranking signal separates.
    it.each(lists)('contains no excluded seeds in %s', (_name, list) => {
      expect(list.filter((word) => excludedSeeds.has(word))).toEqual([])
    })

    // One row per class that has leaked, named individually so a failure says which one it is.
    it.each([
      ['demonym', 'pygmy'],
      ['lowercased proper noun', 'bible'],
      ['sexual anatomy', 'clitoris'],
      ['blocklist-evading compound', 'whorehouse'],
      ['excretion', 'urinate'],
      ['undress', 'topless'],
      ['drug', 'heroin'],
      ['crude', 'cock'],
      ['graphic violence', 'mutilate'],
      ['demeaning', 'obese'],
    ])('excludes the %s "%s"', (_category, word) => {
      expect([...nouns, ...verbs, ...adjectives]).not.toContain(word)
    })

    // A product decision: these lists are displayed, so GREY is a word the game asks a player to
    // spell, and `greyhound` is here because a find-and-replace breaks it.
    it('ships the American spelling and keeps greyhound', () => {
      expect(adjectives).toContain('gray')
      expect(adjectives).not.toContain('grey')
      expect(nouns).toContain('greyhound')
    })

    // Each row pairs the British form with the American, so dropping the wrong side fails here.
    it.each([
      ['moustache', 'mustache'],
      ['ladybird', 'ladybug'],
      ['windscreen', 'windshield'],
      ['motorway', 'highway'],
      ['dustbin', 'trashcan'],
    ])('ships the American "%s" rather than "%s"', (british, american) => {
      expect(nouns).not.toContain(british)
      expect(nouns).toContain(american)
    })

    // `analogue` has no paired row above: `analog` is tagged Noun at 2.67 and ships on no list, so
    // the exclusion costs the adjective list a word outright.
    it('drops analogue even though analog does not replace it', () => {
      expect(adjectives).not.toContain('analogue')
      expect([...nouns, ...verbs, ...adjectives]).not.toContain('analog')
    })

    // The greyhound row generalized: every word here has a British sense and is an ordinary
    // American word regardless, so keying a sweep on the former empties a tenth of the noun list.
    it('keeps American words that merely have a British sense', () => {
      expect(nouns).toEqual(
        expect.arrayContaining(['biscuit', 'bonnet', 'boot', 'cot', 'pavement', 'plaster', 'torch', 'wardrobe']),
      )
    })
  })

  describe('content', () => {
    it('keeps concrete, imageable nouns', () => {
      expect(nouns).toEqual(expect.arrayContaining(['accordion', 'alligator', 'blowtorch', 'stepladder']))
    })

    it('drops the abstract heads of a frequency-ranked list', () => {
      const abstract = ['way', 'thing', 'case', 'part', 'point', 'fact', 'time', 'year', 'people']
      expect(overlap([...nouns, ...verbs, ...adjectives], abstract)).toEqual([])
    })

    // Dom_Pos mislabels concrete nouns as verbs and ranking by concreteness selects for it;
    // stat/rang/slid each matched an -ed or -ing form of a longer lemma.
    it('keeps mislabeled nouns and truncations out of the verb list', () => {
      const mislabeled = ['absinthe', 'clamshell', 'cornflake', 'escargot', 'rang', 'slid', 'stat']
      expect(overlap(verbs, mislabeled)).toEqual([])
    })

    // Compound nouns are not inflections: a base recovered by stripping a fixed number of
    // characters off anything ending in -ing reads "earring" as ear+ring.
    it('keeps compound nouns that merely end in an inflection-like suffix', () => {
      expect(nouns).toEqual(expect.arrayContaining(['earring', 'riverbed', 'seedling', 'woodshed']))
    })

    // Plurals are waste: dog/dogs spend two of a draw's ten slots on one idea. Across every list,
    // because narrowed to -ing verbs there are almost no candidates and it cannot fail.
    it.each(lists)('keeps a word and its own plural out of %s', (_name, list) => {
      const present = new Set(list)
      const pairs = list.filter((word) =>
        [word.replace(/es$/, ''), word.replace(/s$/, '')].some(
          (base) => base !== word && base.length > 2 && present.has(base),
        ),
      )
      expect(pairs).toEqual([])
    })

    // -ing and -ed forms are duplicates only when their base is a verb: bowling, icing and railing
    // name their own things, where blink/blinked is waste.
    it('keeps nominalizations whose base is a noun', () => {
      expect(nouns).toEqual(expect.arrayContaining(['bowling', 'icing', 'railing']))
    })

    it('drops an -ed or -ing form whose base is a verb in the same list', () => {
      const present = new Set(verbs)
      const pairs = verbs.filter((word) =>
        [word.replace(/ing$/, ''), word.replace(/ing$/, 'e'), word.replace(/ed$/, ''), word.replace(/ed$/, 'e')].some(
          (base) => base !== word && base.length > 2 && present.has(base),
        ),
      )
      expect(pairs).toEqual([])
    })
  })
})
