/*
 * British spellings of words this game ships in their American form.
 *
 * A gate rather than a prompt sentence because ENABLE, the lexicon deciding whether a model's word
 * is a word, carries the British forms as ordinary entries. On the surfaces gated here the player
 * TYPES the string, so a scramble of COLOUR is answered COLOR and marked wrong with no way to
 * discover why. Matching is whole-token, so GREYHOUND survives GREY and every inflection to be
 * caught must be written out.
 *
 * An entry earns its place by being wrong in American English, not by being more common in Britain,
 * so these stay out: AXE, DOUGHNUT, GREYHOUND, CATALOGUE, DIALOGUE, MONOLOGUE, WHISKY, OMELETTE,
 * SABRE and the -ISE verbs that were never -IZE (ADVISE, EXERCISE, SURPRISE, FRANCHISE, COMPROMISE,
 * MERCHANDISE, TELEVISE, SUPERVISE, ENTERPRISE). Likewise ANALYSES (the American plural of
 * ANALYSIS), THEATRICAL (identical in both dialects) and HUMOUROUS (a misspelling everywhere).
 *
 * Entries are single uppercase A-Z tokens. The tokenizer in model-output-checks.ts splits on
 * letter-and-digit runs, so a space or a hyphen in an entry makes it permanently unmatchable.
 */
export const britishSpellings: ReadonlySet<string> = new Set([
  // -OUR for -OR, and the inflections, because matching has no stemming.
  'ARMOUR',
  'ARMOURED',
  'ARMOURS',
  'BEHAVIOUR',
  'BEHAVIOURAL',
  'BEHAVIOURS',
  'CANDOUR',
  'CLAMOUR',
  'CLAMOURED',
  'CLAMOURS',
  'COLOUR',
  'COLOURED',
  'COLOURFUL',
  'COLOURING',
  'COLOURLESS',
  'COLOURS',
  'DEMEANOUR',
  'ENDEAVOUR',
  'ENDEAVOURS',
  'FAVOUR',
  'FAVOURABLE',
  'FAVOURED',
  'FAVOURITE',
  'FAVOURITES',
  'FAVOURS',
  'FERVOUR',
  'FLAVOUR',
  'FLAVOURED',
  'FLAVOURS',
  'HARBOUR',
  'HARBOURS',
  'HONOUR',
  'HONOURABLE',
  'HONOURED',
  'HONOURS',
  'HUMOUR',
  'HUMOURS',
  'LABOUR',
  'LABOURED',
  'LABOURER',
  'LABOURERS',
  'LABOURS',
  'NEIGHBOUR',
  'NEIGHBOURHOOD',
  'NEIGHBOURING',
  'NEIGHBOURS',
  'ODOUR',
  'ODOURS',
  'PARLOUR',
  'PARLOURS',
  'RANCOUR',
  'RUMOUR',
  'RUMOURS',
  'SAVIOUR',
  'SAVIOURS',
  'SAVOUR',
  'SAVOURED',
  'SAVOURS',
  'SPLENDOUR',
  'TUMOUR',
  'TUMOURS',
  'VALOUR',
  'VAPOUR',
  'VAPOURS',
  'VIGOUR',

  // -RE for -ER. CENTRE and METRE carry the compounds because the bare token is what gets matched.
  'CALIBRE',
  'CENTRE',
  'CENTRED',
  'CENTRES',
  'FIBRE',
  'FIBRES',
  'LITRE',
  'LITRES',
  'LUSTRE',
  'MANOEUVRE',
  'MANOEUVRES',
  'METRE',
  'METRES',
  'SCEPTRE',
  'SOMBRE',
  'SPECTRE',
  'SPECTRES',
  'THEATRE',
  'THEATRES',

  // -CE for -SE. PRACTISE is the verb only; PRACTICE the noun is correct in both dialects.
  'DEFENCE',
  'DEFENCES',
  'LICENCE',
  'LICENCES',
  'OFFENCE',
  'OFFENCES',
  'PRACTISE',
  'PRACTISED',
  'PRACTISES',
  'PRETENCE',

  // -ISE/-YSE for -IZE/-YZE. Only verbs that are -IZE in American English; see the header.
  'AGONISE',
  'ANALYSE',
  'ANALYSED',
  'APOLOGISE',
  'APOLOGISED',
  'CATEGORISE',
  'CIVILISE',
  'CRITICISE',
  'CRITICISED',
  'CUSTOMISE',
  'EMPHASISE',
  'EMPHASISED',
  'MEMORISE',
  'MINIMISE',
  'MOBILISE',
  'NORMALISE',
  'ORGANISE',
  'ORGANISED',
  'ORGANISES',
  'PARALYSE',
  'PARALYSED',
  'PRIORITISE',
  'RANDOMISE',
  'REALISE',
  'REALISED',
  'REALISES',
  'RECOGNISE',
  'RECOGNISED',
  'RECOGNISES',
  'SPECIALISE',
  'STANDARDISE',
  'SUMMARISE',
  'SYMPATHISE',
  'UTILISE',

  // Doubled L before a suffix.
  'CANCELLED',
  'CANCELLING',
  'COUNSELLOR',
  'COUNSELLORS',
  'FUELLED',
  'JEWELLERY',
  'LABELLED',
  'LABELLING',
  'MARVELLOUS',
  'MODELLING',
  'SIGNALLED',
  'TRAVELLED',
  'TRAVELLER',
  'TRAVELLERS',
  'TRAVELLING',
  'WOOLLEN',

  // Everything else, spelling and vocabulary together: a word that is simply not the American one.
  'ALUMINIUM',
  'AEROPLANE',
  'ANTICLOCKWISE',
  'CHEQUE',
  'CHEQUES',
  'DRAUGHT',
  'DRAUGHTS',
  'DUSTBIN',
  'DUSTBINS',
  'GAOL',
  'GREY',
  'KERB',
  'KERBS',
  'LADYBIRD',
  'LADYBIRDS',
  'MOULD',
  'MOULDS',
  'MOULDY',
  'MOUSTACHE',
  'MOUSTACHES',
  'MOTORWAY',
  'MOTORWAYS',
  'PLOUGH',
  'PLOUGHED',
  'PLOUGHS',
  'PYJAMAS',
  'SCEPTIC',
  'SCEPTICAL',
  'SMOULDER',
  'SMOULDERING',
  'STOREY',
  'STOREYS',
  'TYRE',
  'TYRES',
  'WINDSCREEN',
  'WINDSCREENS',
])
