import { chargedWords } from '../assets/blocklist'

// THE CHARGED-TERM LIST THIS REPO ACTUALLY GATES ON: the vendored `chargedWords` plus the entries
// below. Every caller reads `chargedTerms`; nothing outside this file reads `chargedWords` directly.
//
// WHY NOT JUST EDIT src/assets/blocklist.ts. That file is a byte-identical copy of
// `connections-api/src/assets/blocklist.ts`, and src/assets/README.md states the rule as a universal
// claim about the whole directory rather than a description of its current contents: "This directory
// is closed to originals ... a lull-original here does not merely add a row: it falsifies the
// sentence that gives every OTHER file its integrity story." Widening it in place would put the two
// repos silently out of sync AND cost `nouns.ts`, `verbs.ts` and `adjectives.ts` the only mechanism
// holding their copies together. So the additions live beside the code that reads them --
// utils/model-output-checks.ts -- and the vendored copy stays diffable. When `connections-api`
// adopts these, the right move is to add them THERE, regenerate, re-copy, and delete the duplicates
// from the list below; until then the union is what every gate must read.
//
// WHY THE ADDITIONS ARE ENUMERATED RATHER THAN STEMMED. Matching is whole-token and always has been,
// because ASSESS, COCKTAIL and SCUNTHORPE are legitimate puzzle words and substring matching kills
// them. A stemmer is substring matching wearing a hat: any rule that turns FUCKS into FUCK also turns
// SHITAKE-adjacent innocents into hits, and it fails on exactly the forms that caused this list to be
// widened -- NIGGA is not an inflection of NIGGER by any stemming rule, and TRANNIE is not one of
// TRANNY. An enumerated list is longer to read and cannot surprise anyone.
//
// THE COST OF WHOLE-TOKEN IS PAID DELIBERATELY, per entry, and these are the ones worth naming:
// CHINK ("a chink of light"), SPICK ("spick and span"), GIMP (a braid), DYKE (an embankment, already
// vendored) and RETARD (already vendored, and a real verb in engineering and music) are all
// legitimate English words that this list nonetheless rejects. A puzzle is one word out of a
// 76,000-word pool; a slur shipped as the answer is a ship-blocker. NIGGARD and NIGGARDLY are
// innocent by etymology and are blocked anyway, for the same reason.
//
// DELIBERATELY ABSENT, so nobody re-derives the omission from an incident later: QUEER (reclaimed,
// and "queer" for "strange" is ordinary English), GYP and GYPPED (slur by origin, ordinary by use),
// SPADE, CRACKER, GRINGO, NIP, SLAG, TART, TIT and TITS (every one of them far more often the
// innocent sense), CRIPPLE and LAME (common verbs and adjectives), MONGOL (an ethnonym, unlike
// MONGOLOID) and NAZI (a historical noun). Each of those costs more in false rejections than it buys.
//
// Entries must be single uppercase A-Z tokens: the tokenizer in model-output-checks.ts splits on
// letter-and-digit runs, so a hyphen or a space in an entry makes it permanently unmatchable.
export const additionalChargedWords: Set<string> = new Set([
  // Inflections, plurals, compounds and spelling variants of the 21 vendored entries. This is the
  // half the build-time key filter could never have covered: NIGGER is listed and NIGGA is not,
  // TRANNY is listed and TRANNIE is not, WANKER is listed and WANKERS is not -- and each of those is
  // a DIFFERENT letter multiset, so a filter keyed on the listed form's sorted letters does not see
  // it. The eight vendored four-letter entries are worse still: CUNT, FUCK, SHIT, SLUT, SPIC, TWAT,
  // DYKE and JIZZ cannot match any key in this type's 5-9 letter window at all, while their
  // five-letter plurals sit squarely inside it.
  'ARSE',
  'ARSED',
  'ARSEHOLES',
  'ARSES',
  'ARSEWIPE',
  'ARSEWIPES',
  'ASSHATS',
  'ASSHAT',
  'ASSHOLES',
  'ASSWIPE',
  'ASSWIPES',
  'BASTARDS',
  'BITCHED',
  'BITCHES',
  'BITCHIER',
  'BITCHIEST',
  'BITCHING',
  'BITCHY',
  'BOLLOCK',
  'BOLLOCKED',
  'BOLLOCKING',
  'BULLSHIT',
  'BULLSHITS',
  'BULLSHITTED',
  'BULLSHITTER',
  'BULLSHITTERS',
  'BULLSHITTING',
  'CLUSTERFUCK',
  'CLUSTERFUCKS',
  'CUNTS',
  'CUNTY',
  'DIPSHIT',
  'DIPSHITS',
  'DOUCHEBAG',
  'DOUCHEBAGS',
  'DOUCHES',
  'DUMBASS',
  'DUMBASSES',
  'DYKES',
  'FAG',
  'FAGGOTRY',
  'FAGGOTS',
  'FAGGY',
  'FAGS',
  'FATASS',
  'FATASSES',
  'FUCKED',
  'FUCKER',
  'FUCKERS',
  'FUCKING',
  'FUCKS',
  'FUCKUP',
  'FUCKUPS',
  'FUCKWIT',
  'FUCKWITS',
  'HARDASS',
  'HARDASSES',
  'HORSESHIT',
  'JIZZED',
  'JIZZES',
  'JIZZING',
  'LARDASS',
  'LARDASSES',
  'MOTHERFUCKER',
  'MOTHERFUCKERS',
  'MOTHERFUCKING',
  'NIGGA',
  'NIGGAH',
  'NIGGAHS',
  'NIGGAS',
  'NIGGAZ',
  'NIGGERS',
  'NIGGUH',
  'NIGGUHS',
  'PUSSIES',
  'RETARDATE',
  'RETARDATES',
  'RETARDATION',
  'RETARDED',
  'RETARDS',
  'SHITBAG',
  'SHITBAGS',
  'SHITE',
  'SHITES',
  'SHITFACE',
  'SHITHEAD',
  'SHITHEADS',
  'SHITHOLE',
  'SHITHOLES',
  'SHITS',
  'SHITTED',
  'SHITTING',
  'SHITTY',
  'SLUTS',
  'SLUTTIER',
  'SLUTTIEST',
  'SLUTTY',
  'SMARTASS',
  'SMARTASSES',
  'SONOFABITCH',
  'SPICK',
  'SPICKS',
  'SPICS',
  'TRANNIE',
  'TRANNIES',
  'TWATS',
  'WANK',
  'WANKED',
  'WANKERS',
  'WANKING',
  'WANKS',
  'WANKY',
  'WHORED',
  'WHOREHOUSE',
  'WHOREHOUSES',
  'WHOREMONGER',
  'WHOREMONGERS',
  'WHORES',
  'WHORING',

  // Racial and ethnic slurs. Absent from the vendored list ENTIRELY -- it was "seeded with
  // unambiguous profanity" and never extended -- so this is a category gap rather than an inflection
  // gap. NIGGARD and its forms are here despite being innocent by etymology: the gate exists to stop
  // a string reaching a player's screen, and that one does not survive being read aloud.
  'ABBO',
  'ABBOS',
  'BEANER',
  'BEANERS',
  'CHINAMAN',
  'CHINAMEN',
  'CHINK',
  'CHINKS',
  'CHINKY',
  'COOLIE',
  'COOLIES',
  'COON',
  'COONASS',
  'COONS',
  'DAGO',
  'DAGOES',
  'DAGOS',
  'DARKEY',
  'DARKEYS',
  'DARKIE',
  'DARKIES',
  'DARKY',
  'GOLLIWOG',
  'GOLLIWOGS',
  'GOLLYWOG',
  'GOLLYWOGS',
  'GOOK',
  'GOOKS',
  'HALFBREED',
  'HALFBREEDS',
  'HEEB',
  'HEEBS',
  'HONKEY',
  'HONKEYS',
  'HONKIE',
  'HONKIES',
  'HONKY',
  'INJUN',
  'INJUNS',
  'JAP',
  'JAPS',
  'JEWBOY',
  'JEWBOYS',
  'JIGABOO',
  'JIGABOOS',
  'KAFFIR',
  'KAFFIRS',
  'KAFIR',
  'KAFIRS',
  'KIKE',
  'KIKES',
  'MULATTO',
  'MULATTOES',
  'MULATTOS',
  'NEGRESS',
  'NEGRESSES',
  'NEGRO',
  'NEGROES',
  'NEGROS',
  'NIGGARD',
  'NIGGARDLINESS',
  'NIGGARDLY',
  'NIGGARDS',
  'NIGNOG',
  'NIGNOGS',
  'OCTOROON',
  'OCTOROONS',
  'PAKI',
  'PAKIS',
  'PICANINNY',
  'PICCANINNY',
  'PICKANINNIES',
  'PICKANINNY',
  'POLACK',
  'POLACKS',
  'QUADROON',
  'QUADROONS',
  'RAGHEAD',
  'RAGHEADS',
  'REDSKIN',
  'REDSKINS',
  'SAMBO',
  'SAMBOS',
  'SQUAW',
  'SQUAWS',
  'TOWELHEAD',
  'TOWELHEADS',
  'WETBACK',
  'WETBACKS',
  'WHITEY',
  'WHITEYS',
  'WOG',
  'WOGS',
  'WOP',
  'WOPS',
  'YID',
  'YIDS',

  // Disability slurs. The other category the vendored list has no row for. RETARD is vendored and its
  // inflections are above; everything here is a term the vendored list never reached.
  'CRETIN',
  'CRETINOUS',
  'CRETINS',
  'GIMP',
  'GIMPS',
  'IMBECILE',
  'IMBECILES',
  'IMBECILIC',
  'MIDGET',
  'MIDGETS',
  'MONGOLOID',
  'MONGOLOIDS',
  'MORON',
  'MORONIC',
  'MORONS',
  'SPASTIC',
  'SPASTICS',
  'SPAZ',
  'SPAZZ',
  'SPAZZES',
  'SPAZZY',

  // Sexual, gender-identity and indecency terms the vendored seed did not reach. TRANNY is vendored;
  // TRANNIE and TRANNIES are above with the other inflections.
  'BIMBO',
  'BIMBOS',
  'BLOWJOB',
  'BLOWJOBS',
  'BUGGER',
  'BUGGERED',
  'BUGGERING',
  'BUGGERS',
  'CUMSHOT',
  'CUMSHOTS',
  'CUNNILINGUS',
  'DICKHEAD',
  'DICKHEADS',
  'DICKWAD',
  'DICKWADS',
  'DILDO',
  'DILDOES',
  'DILDOS',
  'FELCH',
  'FELCHING',
  'FELLATIO',
  'GODDAM',
  'GODDAMN',
  'GODDAMNED',
  'HANDJOB',
  'HANDJOBS',
  'HOMO',
  'HOMOS',
  'KNOBHEAD',
  'KNOBHEADS',
  'LADYBOY',
  'LADYBOYS',
  'MINGE',
  'MINGER',
  'MINGERS',
  'MINGES',
  'NUTSACK',
  'NUTSACKS',
  'PISS',
  'PISSED',
  'PISSES',
  'PISSHEAD',
  'PISSHEADS',
  'PISSING',
  'PISSY',
  'POOF',
  'POOFS',
  'POOFTER',
  'POOFTERS',
  'POOVE',
  'POOVES',
  'PORN',
  'PORNO',
  'PORNOS',
  'RAPIST',
  'RAPISTS',
  'RIMJOB',
  'RIMJOBS',
  'SCUMBAG',
  'SCUMBAGS',
  'SHEMALE',
  'SHEMALES',
  'SKANK',
  'SKANKS',
  'SKANKY',
  'SODOMITE',
  'SODOMITES',
  'TITTIES',
  'TITTY',
])

/**
 * THE SET EVERY GATE READS. The vendored copy unioned with the additions above.
 *
 * Built once at module init from two frozen literals, so there is no ordering hazard and no way for a
 * caller to see a partially-composed set. It is the ONLY export anything outside this file should
 * gate on: `chargedWords` alone is 21 entries and misses every inflection, and
 * `additionalChargedWords` alone misses the 21.
 */
export const chargedTerms: Set<string> = new Set([...chargedWords, ...additionalChargedWords])
