/*
 * Regenerates src/assets/{nouns,verbs,adjectives}.ts from the Brysbaert concreteness norms.
 *
 * Run with: npm run build-word-lists
 *
 * These lists are inspiration seeds seen by the model on every generation (getModelContext samples
 * 10/8/5 of them into the context). Their job is to knock the model out of its default attractor
 * basins, so what matters is that the words are CONCRETE and IMAGEABLE -- "blowtorch" and
 * "stepladder" push somewhere, "way" and "thing" do not. The lists this replaced were ranked by
 * corpus frequency, which selects for exactly the wrong property.
 */
import { createHash } from 'crypto'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import { chargedTerms } from '../src/utils/charged-terms'
import { excludedSeeds } from './excluded-seeds'

export const DATA_FILE = join(__dirname, 'data', 'concreteness-brysbaert-2014.txt')
const ASSETS_DIR = join(__dirname, '..', 'src', 'assets')

// Pinned so a swapped, truncated, or re-encoded dataset fails loudly instead of quietly producing
// different lists. The source ships CRLF; scripts/data/README.md documents the LF normalization
// this hash is taken over.
const DATA_SHA256 = '08196a05dcaa774d49eaaf0fdf8617d4ed6cf26d2d95d92a1da9afbcecfbdf10'

const CITATION = `// Generated by scripts/build-word-lists.ts -- do not edit by hand.
// To remove a word, add it to scripts/excluded-seeds.ts and regenerate. Edits made here are
// silently reverted by the next run.
//
// A filtered subset of the concreteness ratings in:
//   Brysbaert, M., Warriner, A.B., & Kuperman, V. (2014). Concreteness ratings for 40 thousand
//   generally known English word lemmas. Behavior Research Methods, 46, 904-911.
//   https://doi.org/10.3758/s13428-013-0403-5
// Used and modified under CC BY 4.0 -- https://creativecommons.org/licenses/by/4.0/`

// Columns in the source file, which is tab-delimited with a header row.
const COLUMN = { bigram: 1, concreteness: 2, partOfSpeech: 8, word: 0 }

const MAX_LENGTH = 12
const MIN_LENGTH = 3

// A single global cutoff does not work: verbs and adjectives are inherently less concrete than
// nouns, so a 4.0 threshold yields 5770 nouns but only 471 verbs and 226 adjectives -- starving two
// of the three lists.
//
// Verbs are the awkward list. Dom_Pos is noisy and mislabels concrete nouns as verbs (escargot,
// clamshell, absinthe, ocelot all arrive tagged Verb), and ranking by concreteness selects FOR that
// error, because a mislabeled concrete noun outscores every real verb. requireVerbal below filters
// them out morphologically, which costs enough of the pool that the verb threshold has to drop to
// 3.0 and the cap to 500 to fill. A shorter list of real verbs beats a longer list of mislabeled
// nouns -- only 8 are sampled per generation either way. The cap deliberately leaves headroom above
// the eligible pool, because the denylist is expected to grow and an equality-to-cap check turns
// every future exclusion into a build failure.
export interface ListSpec {
  // The minimum a healthy build produces. SEPARATED FROM `cap` on 2026-09-05, because the two were
  // the same number only while every pool overflowed its cap -- the check below read
  // `words.length < spec.cap`, which is a FLOOR test wearing the cap's name and silently stopped
  // being one the moment a list was allowed to take everything eligible.
  //
  // It is not decoration. scripts/data/README.md documents a CRLF footgun that makes all three
  // lists come out EMPTY, and an empty list feeds [undefined x 10] into the model context rather
  // than failing the build. Set well under the measured yield: it exists to catch a collapse, not
  // to pin a count, and a floor that tracks the exact yield fails the build every time someone adds
  // a word to excluded-seeds.ts.
  floor: number
  cap: number
  name: string
  partOfSpeech: string
  requireVerbal: boolean
  threshold: number
}

export const SPECS: ListSpec[] = [
  // MEASURED 2026-09-05, not chosen. These lists are the only thing keeping two days of generated
  // content apart, and the model maps a seed to a theme very nearly one-for-one -- so the collision
  // rate of a pool IS the repetition rate of the game downstream. Over a seven-day span the old
  // sizes gave, per pair of days, a 4.9% chance of sharing a noun, 4.9% an adjective and 12.2% a
  // verb: about one repeated noun and two-and-a-half repeated verbs a week.
  //
  // NOUNS ARE A FREE WIN and the threshold does not move: 3193 words clear 4.5, so the CAP was
  // throwing away 1193 words of identical quality. It is gone rather than raised, because a cap set
  // below what the filter admits is a number with nothing behind it.
  //
  // VERBS AND ADJECTIVES COST CONCRETENESS, which is the honest trade. 3.0 -> 2.5 takes verbs
  // 595 -> 840 and admits crave, dazzle, grapple, whittle -- and also oppose, repay, heighten, which
  // are weak seeds. 3.5 -> 3.0 takes adjectives 616 -> 1316 and admits seafaring, clammy, gangly,
  // durable. The adjective floor is where the clinical anatomy lives; see excluded-seeds.ts.
  {
    cap: Number.MAX_SAFE_INTEGER,
    floor: 2500,
    name: 'nouns',
    partOfSpeech: 'Noun',
    requireVerbal: false,
    threshold: 4.5,
  },
  {
    cap: Number.MAX_SAFE_INTEGER,
    floor: 700,
    name: 'verbs',
    partOfSpeech: 'Verb',
    requireVerbal: true,
    threshold: 2.5,
  },
  {
    cap: Number.MAX_SAFE_INTEGER,
    floor: 1000,
    name: 'adjectives',
    partOfSpeech: 'Adjective',
    requireVerbal: false,
    threshold: 3.0,
  },
]

// Concreteness bands the cap draws from proportionally, per the spec's derivation step 11.
//
// Measured effect, so nobody overestimates it: the per-list threshold already does most of the
// work. For nouns the band draw admits the 4.56-4.70 concreteness slice a top slice would cut; for
// verbs it is nearly a no-op (the pool barely exceeds the cap). It is kept because it is the
// behaviour the spec specifies and because it degrades gracefully if a threshold is ever lowered to
// widen a pool -- not because it transforms the output.
const BAND_COUNT = 5

export interface Entry {
  concreteness: number
  partOfSpeech: string
  word: string
}

export const parseEntries = (contents: string): Entry[] =>
  contents
    .split('\n')
    .slice(1)
    .filter((line) => line.length > 0)
    .map((line) => line.split('\t'))
    // Bigram === '1' marks a two-word expression. Those are not seeds.
    .filter((fields) => fields[COLUMN.bigram] === '0')
    .map((fields) => ({
      concreteness: Number(fields[COLUMN.concreteness]),
      partOfSpeech: fields[COLUMN.partOfSpeech],
      word: fields[COLUMN.word],
    }))
    .filter((entry) => !Number.isNaN(entry.concreteness))

// Candidate inflected forms of a base word. Used two ways: to decide whether a Verb-tagged lemma
// behaves like a verb (does any inflection of it exist in the corpus?), and to decide whether a
// word is itself an inflection of something already selected.
const inflectionsOf = (word: string): string[] => {
  // Deliberately NO -s or -es form. Noun plurals and third-person verbs share that suffix, so
  // including it lets "cornflake" pass on the strength of "cornflakes". Only -ed and -ing are
  // verb-exclusive, and requiring one of those is what actually separates a verb from a noun.
  const forms = [`${word}ed`, `${word}ing`]
  if (word.endsWith('e')) {
    forms.push(`${word.slice(0, -1)}ing`, `${word}d`)
  }
  if (word.endsWith('y')) {
    forms.push(`${word.slice(0, -1)}ied`)
  }
  const last = word.at(-1) as string
  const previous = word.at(-2) as string
  // Consonant-doubling: hop -> hopped, hopping
  if (!'aeiou'.includes(last) && 'aeiou'.includes(previous)) {
    forms.push(`${word}${last}ed`, `${word}${last}ing`)
  }
  return forms
}

// Plausible base forms of a possibly-inflected word, used to drop base/inflection pairs.
//
// `verbBases` are the -ed/-ing readings. They are only consulted when the recovered base is tagged
// Verb in the corpus, because -ed/-ing are verbal inflections: without that guard "earring" is read
// as ear+ring and dropped in favour of the noun "ear", and duckling, riverbed, seedling, bullring,
// woodshed, and featherbed all go the same way. None of those is an inflection of anything.
//
// The doubled-consonant readings (hop -> hopping) are deliberately absent. They are genuinely
// ambiguous -- "earring" has a real doubled r -- and losing a handful of hop/hopping pairs is a far
// better trade than losing concrete compound nouns.
const nounBases = (word: string): string[] => {
  const bases: string[] = []
  if (word.endsWith('es')) {
    bases.push(word.slice(0, -2), word.slice(0, -1))
  }
  if (word.endsWith('s') && !word.endsWith('ss')) {
    bases.push(word.slice(0, -1))
  }
  return bases.filter((base) => base.length > 2)
}

const verbBases = (word: string): string[] => {
  const bases: string[] = []
  if (word.endsWith('ing')) {
    bases.push(word.slice(0, -3), `${word.slice(0, -3)}e`)
  }
  if (word.endsWith('ed')) {
    bases.push(word.slice(0, -2), word.slice(0, -1))
  }
  return bases.filter((base) => base.length > 2)
}

// True when some corpus lemma LONGER than `word` also generates `form`. That is the signal that
// `word` is a truncation rather than a lemma: "stated" is reachable from "state", so the Verb-tagged
// "stat" is an abbreviation, not a verb. Same for rang/range and slid/slide.
const hasBetterBase = (form: string, word: string, vocabulary: Set<string>): boolean =>
  verbBases(form).some((base) => base !== word && base.length > word.length && vocabulary.has(base))

// Proportional draw across concreteness bands. Deterministic: no randomness, so regenerating the
// lists from the same dataset always produces the same output.
const drawAcrossBands = (entries: Entry[], cap: number): Entry[] => {
  if (entries.length <= cap) {
    return entries
  }
  const ranked = entries.toSorted(
    (left, right) => right.concreteness - left.concreteness || left.word.localeCompare(right.word),
  )
  const bandSize = Math.ceil(ranked.length / BAND_COUNT)
  const bands = Array.from({ length: BAND_COUNT }, (_, index) => ranked.slice(index * bandSize, (index + 1) * bandSize))

  const drawn: Entry[] = []
  // Round-robin rather than a per-band quota, so rounding never leaves the list short of the cap.
  for (let position = 0; drawn.length < cap; position += 1) {
    for (const band of bands) {
      if (position < band.length && drawn.length < cap) {
        drawn.push(band[position])
      }
    }
  }
  return drawn
}

export const selectFor = (
  entries: Entry[],
  spec: ListSpec,
  vocabulary: Set<string>,
  partOfSpeech: Map<string, string>,
): string[] => {
  const eligible = entries
    .filter((entry) => entry.partOfSpeech === spec.partOfSpeech)
    .filter((entry) => entry.concreteness > spec.threshold)
    // Lowercase letters only. NOTE: this removes hyphenates, apostrophes, and digits. It does NOT
    // remove proper nouns -- the dataset stores every word lowercase, so there is no capitalization
    // left to check. excludedSeeds is what keeps demonyms out.
    .filter((entry) => /^[a-z]+$/.test(entry.word))
    .filter((entry) => entry.word.length >= MIN_LENGTH && entry.word.length <= MAX_LENGTH)
    // Whole-token match against blocklist.ts, so a charged term cannot enter through the back door
    // as an inspiration seed.
    //
    // NARROWER THAN THE RUNTIME GATE, AND KNOWN TO LEAK. Every check over model output reads
    // `chargedTerms` -- blocklist.ts unioned with the enumerated closure in utils/charged-terms.ts --
    // THE UNION, not the 21 base forms. Whole-token match against the SAME list every runtime gate
    // reads, so a charged term cannot enter through the back door as an inspiration seed.
    //
    // It read `chargedWords` until 2026-09-05 and the gap had shipped: `fucking` and `horseshit` are
    // both in `chargedTerms` and in neither base form, so both cleared this filter and sat in the
    // committed lists, sampled into the corpus prompt on every call. Neither could reach a player --
    // every generated string is checked against the union downstream -- which is exactly why it went
    // unnoticed: the backstop held while the thing that was supposed to stop it never fired.
    //
    // A filter that screens against a NARROWER list than the gate it feeds is not a filter, it is a
    // second opinion nobody asked for. Removing the two words costs 2 of 5312.
    .filter((entry) => !chargedTerms.has(entry.word.toUpperCase()))
    .filter((entry) => !excludedSeeds.has(entry.word))
    // Dom_Pos mislabels concrete nouns as verbs. A real English verb almost always has at least one
    // inflection somewhere in the corpus; escargot and clamshell have none.
    .filter(
      (entry) =>
        !spec.requireVerbal ||
        inflectionsOf(entry.word).some((form) => vocabulary.has(form) && !hasBetterBase(form, entry.word, vocabulary)),
    )

  // Drop base/inflection pairs within the list. blink/blinked/blinking/blinks were all present
  // before this, wasting four of the ten slots a draw has on one idea.
  const present = new Set(eligible.map((entry) => entry.word))
  const isVerb = (word: string): boolean => partOfSpeech.get(word) === 'Verb'
  const deduplicated = eligible.filter(
    (entry) =>
      !nounBases(entry.word).some((base) => present.has(base)) &&
      !verbBases(entry.word).some((base) => present.has(base) && isVerb(base)),
  )

  return drawAcrossBands(deduplicated, spec.cap)
    .map((entry) => entry.word)
    .toSorted()
}

export const renderFile = (name: string, words: string[]): string => {
  // Asserted here rather than relying on selectFor's filter: this function interpolates straight
  // into single quotes, so one apostrophe would emit a file that does not parse.
  const unsafe = words.filter((word) => !/^[a-z]+$/.test(word))
  if (unsafe.length > 0) {
    throw new Error(`Refusing to render unquotable words: ${unsafe.join(', ')}`)
  }
  return `${CITATION}\n\nexport const ${name}: string[] = [\n${words.map((word) => `  '${word}',`).join('\n')}\n]\n`
}

export const main = (): void => {
  const contents = readFileSync(DATA_FILE, 'utf-8')

  const actual = createHash('sha256').update(contents).digest('hex')
  if (actual !== DATA_SHA256) {
    throw new Error(`Dataset hash mismatch. Expected ${DATA_SHA256}, got ${actual}`)
  }
  console.log(`Dataset sha256: ${actual}`)

  const entries = parseEntries(contents)
  console.log(`Parsed ${entries.length} single-word entries`)

  // Every word in the corpus, not just the eligible ones -- the verb check asks whether an
  // inflection exists anywhere, and inflections are usually far less concrete than their base.
  const vocabulary = new Set(entries.map((entry) => entry.word))

  const partOfSpeech = new Map(entries.map((entry) => [entry.word, entry.partOfSpeech]))
  const lists = SPECS.map((spec) => ({ spec, words: selectFor(entries, spec, vocabulary, partOfSpeech) }))

  // Dom_Pos assigns one part of speech per lemma, so disjointness should fall out for free.
  // Asserted rather than assumed: the previous lists overlapped in 307 places and nothing caught it.
  for (let left = 0; left < lists.length; left += 1) {
    for (let right = left + 1; right < lists.length; right += 1) {
      const rightSet = new Set(lists[right].words)
      const shared = lists[left].words.filter((word) => rightSet.has(word))
      if (shared.length > 0) {
        throw new Error(`${lists[left].spec.name} and ${lists[right].spec.name} share: ${shared.join(', ')}`)
      }
    }
  }

  // Validate every list BEFORE writing any of them. Interleaving the check with the write leaves
  // src/assets half-regenerated when a later list comes up short -- nouns already rewritten, verbs
  // not. Throwing rather than warning is deliberate: the CRLF footgun in scripts/data/README.md
  // makes all three lists come out empty, and an empty list would feed [undefined x 10] into the
  // model context instead of failing the build.
  for (const { spec, words } of lists) {
    if (words.length < spec.floor) {
      throw new Error(`${spec.name} yielded ${words.length}, under its floor of ${spec.floor}`)
    }
  }

  for (const { spec, words } of lists) {
    writeFileSync(join(ASSETS_DIR, `${spec.name}.ts`), renderFile(spec.name, words))
    console.log(`Wrote ${spec.name}.ts with ${words.length} words`)
  }
}

// Guarded so the module can be imported by tests without writing to src/assets.
if (require.main === module) {
  main()
}
