/*
 * Regenerates src/assets/{nouns,verbs,adjectives}.ts from the Brysbaert concreteness norms; run
 * with `npm run build-word-lists`. These are inspiration seeds sampled into the model context on
 * every generation (getModelContext takes 10/8/5), there to knock it out of its default attractor
 * basins. Rank by concreteness, never frequency: "blowtorch" pushes somewhere, "thing" does not.
 */
import { createHash } from 'crypto'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import { chargedTerms } from '../src/utils/charged-terms'
import { excludedSeeds } from './excluded-seeds'

export const DATA_FILE = join(__dirname, 'data', 'concreteness-brysbaert-2014.txt')
const ASSETS_DIR = join(__dirname, '..', 'src', 'assets')

// Pinned so a swapped dataset fails loudly; taken over the LF normalization in data/README.md.
const DATA_SHA256 = '08196a05dcaa774d49eaaf0fdf8617d4ed6cf26d2d95d92a1da9afbcecfbdf10'

const CITATION = `// Generated by scripts/build-word-lists.ts -- do not edit by hand.
// To remove a word, add it to scripts/excluded-seeds.ts and regenerate. Edits made here are
// silently reverted by the next run.
//
// A filtered subset of the concreteness ratings in:
//   Brysbaert, M., Warriner, A.B., & Kuperman, V. (2014). Concreteness ratings for 40 thousand
//   generally known English word lemmas. Behavior Research Methods, 46, 904-911.
//   https://doi.org/10.3758/s13428-013-0403-5
// Used and modified under CC BY 4.0 -- https://creativecommons.org/licenses/by/4.0/`

// Columns in the source file: tab-delimited, one header row.
const COLUMN = { bigram: 1, concreteness: 2, partOfSpeech: 8, word: 0 }

const MAX_LENGTH = 12
const MIN_LENGTH = 3

// Per-list thresholds: one 4.0 cutoff yields 5770 nouns but only 471 verbs and 226 adjectives.
export interface ListSpec {
  // The minimum a healthy build produces, never `cap` reused, set well under the measured yield:
  // the CRLF footgun in data/README.md empties all three lists, and empty feeds the model context.
  floor: number
  cap: number
  name: string
  partOfSpeech: string
  requireVerbal: boolean
  threshold: number
}

export const SPECS: ListSpec[] = [
  // A seed maps to a theme nearly one-for-one, so pool collisions are the game's repetitions.
  {
    cap: Number.MAX_SAFE_INTEGER,
    floor: 2500,
    name: 'nouns',
    partOfSpeech: 'Noun',
    requireVerbal: false,
    threshold: 4.5,
  },
  {
    cap: Number.MAX_SAFE_INTEGER,
    floor: 700,
    name: 'verbs',
    partOfSpeech: 'Verb',
    requireVerbal: true,
    threshold: 2.5,
  },
  {
    cap: Number.MAX_SAFE_INTEGER,
    floor: 1000,
    name: 'adjectives',
    partOfSpeech: 'Adjective',
    requireVerbal: false,
    threshold: 3.0,
  },
]

// Bands a capped draw pulls from proportionally, so a cap takes a spread rather than a top slice.
const BAND_COUNT = 5

export interface Entry {
  concreteness: number
  partOfSpeech: string
  word: string
}

export const parseEntries = (contents: string): Entry[] =>
  contents
    .split('\n')
    .slice(1)
    .filter((line) => line.length > 0)
    .map((line) => line.split('\t'))
    // Bigram === '1' marks a two-word expression. Those are not seeds.
    .filter((fields) => fields[COLUMN.bigram] === '0')
    .map((fields) => ({
      concreteness: Number(fields[COLUMN.concreteness]),
      partOfSpeech: fields[COLUMN.partOfSpeech],
      word: fields[COLUMN.word],
    }))
    .filter((entry) => !Number.isNaN(entry.concreteness))

const inflectionsOf = (word: string): string[] => {
  // No -s form: nouns share that suffix, so it would let "cornflake" pass on "cornflakes".
  const forms = [`${word}ed`, `${word}ing`]
  if (word.endsWith('e')) {
    forms.push(`${word.slice(0, -1)}ing`, `${word}d`)
  }
  if (word.endsWith('y')) {
    forms.push(`${word.slice(0, -1)}ied`)
  }
  const last = word.at(-1) as string
  const previous = word.at(-2) as string
  if (!'aeiou'.includes(last) && 'aeiou'.includes(previous)) {
    forms.push(`${word}${last}ed`, `${word}${last}ing`)
  }
  return forms
}

// Base forms for dropping base/inflection pairs. Consult `verbBases` only when the recovered base
// is tagged Verb, or "earring" reads as ear+ring and is dropped for "ear".
const nounBases = (word: string): string[] => {
  const bases: string[] = []
  if (word.endsWith('es')) {
    bases.push(word.slice(0, -2), word.slice(0, -1))
  }
  if (word.endsWith('s') && !word.endsWith('ss')) {
    bases.push(word.slice(0, -1))
  }
  return bases.filter((base) => base.length > 2)
}

const verbBases = (word: string): string[] => {
  const bases: string[] = []
  if (word.endsWith('ing')) {
    bases.push(word.slice(0, -3), `${word.slice(0, -3)}e`)
  }
  if (word.endsWith('ed')) {
    bases.push(word.slice(0, -2), word.slice(0, -1))
  }
  return bases.filter((base) => base.length > 2)
}

// True when a longer lemma also generates `form`, so `word` is a truncation: "stated" is "state".
const hasBetterBase = (form: string, word: string, vocabulary: Set<string>): boolean =>
  verbBases(form).some((base) => base !== word && base.length > word.length && vocabulary.has(base))

// Proportional draw across concreteness bands; deterministic, so one dataset gives one output.
const drawAcrossBands = (entries: Entry[], cap: number): Entry[] => {
  if (entries.length <= cap) {
    return entries
  }
  const ranked = entries.toSorted(
    (left, right) => right.concreteness - left.concreteness || left.word.localeCompare(right.word),
  )
  const bandSize = Math.ceil(ranked.length / BAND_COUNT)
  const bands = Array.from({ length: BAND_COUNT }, (_, index) => ranked.slice(index * bandSize, (index + 1) * bandSize))

  const drawn: Entry[] = []
  // Round-robin rather than a per-band quota, so rounding never leaves the list short of the cap.
  for (let position = 0; drawn.length < cap; position += 1) {
    for (const band of bands) {
      if (position < band.length && drawn.length < cap) {
        drawn.push(band[position])
      }
    }
  }
  return drawn
}

export const selectFor = (
  entries: Entry[],
  spec: ListSpec,
  vocabulary: Set<string>,
  partOfSpeech: Map<string, string>,
): string[] => {
  const eligible = entries
    .filter((entry) => entry.partOfSpeech === spec.partOfSpeech)
    .filter((entry) => entry.concreteness > spec.threshold)
    // Removes hyphenates, apostrophes and digits. The dataset is all lowercase, so proper nouns
    // survive this and are excludedSeeds' job.
    .filter((entry) => /^[a-z]+$/.test(entry.word))
    .filter((entry) => entry.word.length >= MIN_LENGTH && entry.word.length <= MAX_LENGTH)
    // `chargedTerms`, the union every runtime gate reads, and never `chargedWords`, the 21 base
    // forms: screening against the narrower list lets `fucking` into the committed assets.
    .filter((entry) => !chargedTerms.has(entry.word.toUpperCase()))
    .filter((entry) => !excludedSeeds.has(entry.word))
    // Dom_Pos tags concrete nouns Verb and concreteness ranking selects for it; escargot has no
    // inflection in the corpus and a real verb does.
    .filter(
      (entry) =>
        !spec.requireVerbal ||
        inflectionsOf(entry.word).some((form) => vocabulary.has(form) && !hasBetterBase(form, entry.word, vocabulary)),
    )

  // Drop base/inflection pairs, or blink/blinked/blinking/blinks spends four of a draw's ten slots.
  const present = new Set(eligible.map((entry) => entry.word))
  const isVerb = (word: string): boolean => partOfSpeech.get(word) === 'Verb'
  const deduplicated = eligible.filter(
    (entry) =>
      !nounBases(entry.word).some((base) => present.has(base)) &&
      !verbBases(entry.word).some((base) => present.has(base) && isVerb(base)),
  )

  return drawAcrossBands(deduplicated, spec.cap)
    .map((entry) => entry.word)
    .toSorted()
}

export const renderFile = (name: string, words: string[]): string => {
  // Re-asserted: this interpolates into single quotes, so one apostrophe emits an unparseable file.
  const unsafe = words.filter((word) => !/^[a-z]+$/.test(word))
  if (unsafe.length > 0) {
    throw new Error(`Refusing to render unquotable words: ${unsafe.join(', ')}`)
  }
  return `${CITATION}\n\nexport const ${name}: string[] = [\n${words.map((word) => `  '${word}',`).join('\n')}\n]\n`
}

export const main = (): void => {
  const contents = readFileSync(DATA_FILE, 'utf-8')

  const actual = createHash('sha256').update(contents).digest('hex')
  if (actual !== DATA_SHA256) {
    throw new Error(`Dataset hash mismatch. Expected ${DATA_SHA256}, got ${actual}`)
  }
  console.log(`Dataset sha256: ${actual}`)

  const entries = parseEntries(contents)
  console.log(`Parsed ${entries.length} single-word entries`)

  // Every corpus word, not just eligible ones: the verb check asks whether an inflection exists
  // anywhere, and inflections are usually less concrete than their base.
  const vocabulary = new Set(entries.map((entry) => entry.word))

  const partOfSpeech = new Map(entries.map((entry) => [entry.word, entry.partOfSpeech]))
  const lists = SPECS.map((spec) => ({ spec, words: selectFor(entries, spec, vocabulary, partOfSpeech) }))

  // Dom_Pos gives one part of speech per lemma, so disjointness is free -- and unnoticed if lost.
  for (let left = 0; left < lists.length; left += 1) {
    for (let right = left + 1; right < lists.length; right += 1) {
      const rightSet = new Set(lists[right].words)
      const shared = lists[left].words.filter((word) => rightSet.has(word))
      if (shared.length > 0) {
        throw new Error(`${lists[left].spec.name} and ${lists[right].spec.name} share: ${shared.join(', ')}`)
      }
    }
  }

  // Check every list before writing any, or a short list leaves src/assets half-regenerated.
  for (const { spec, words } of lists) {
    if (words.length < spec.floor) {
      throw new Error(`${spec.name} yielded ${words.length}, under its floor of ${spec.floor}`)
    }
  }

  for (const { spec, words } of lists) {
    writeFileSync(join(ASSETS_DIR, `${spec.name}.ts`), renderFile(spec.name, words))
    console.log(`Wrote ${spec.name}.ts with ${words.length} words`)
  }
}

// Guarded so tests can import the module without writing to src/assets.
if (require.main === module) {
  main()
}
