#!/usr/bin/env ts-node
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { chargedTerms } from '../src/utils/charged-terms'

// Derives src/generators/crypticclue/data/known-words.ts from scripts/data/enable.txt, digest-pinned by
// scripts/data/enable.sha256 and shared with scripts/build-anagram-index.ts. Run by hand. `--check`
// re-derives in memory and throws when the committed file differs; CI runs that form, and it is the only
// check on recall -- a test over the committed list cannot see an entry wrongly missing.

const DATA_DIRECTORY = join(__dirname, 'data')

export const SOURCE_PATH = join(DATA_DIRECTORY, 'enable.txt')
export const DIGEST_PATH = join(DATA_DIRECTORY, 'enable.sha256')
export const OUTPUT_PATH = join(__dirname, '..', 'src', 'generators', 'crypticclue', 'data', 'known-words.ts')

// The oracle's band. A cryptic fodder token is an ordinary short word -- `an`, `of` -- so the floor is 2,
// not the answer band's 4; a one-letter token is not in ENABLE and rejects as `unknown-fodder-word`. The
// ceiling of 12 is above any token the clue length cap allows.
export const MIN_LENGTH = 2
export const MAX_LENGTH = 12

// A floor on the committed list's size: an oracle, not a sample. A list that lost most of its entries
// would reject most fair clues as unknown-fodder-word, which reads in the log like a bad model night.
export const MIN_ENTRIES = 100_000

const ENTRY_PATTERN = /^[a-z]+$/

/** The committed digest, read from its own file so the two scripts on this corpus cannot hold two pins. */
export const readPinnedDigest = (digestPath: string = DIGEST_PATH): string => {
  const [digest] = readFileSync(digestPath, 'utf8').trim().split(/\s+/)
  return digest
}

/** The source corpus, one entry per line. Throws -- never warns -- when the digest does not match its pin. */
export const readSource = (sourcePath: string = SOURCE_PATH, digestPath: string = DIGEST_PATH): string[] => {
  const contents = readFileSync(sourcePath)
  const digest = createHash('sha256').update(contents).digest('hex')
  const pinned = readPinnedDigest(digestPath)
  if (digest !== pinned) {
    throw new Error(`${sourcePath} does not match its pin: expected ${pinned}, read ${digest}`)
  }
  return contents.toString('utf8').split('\n').filter(Boolean)
}

/**
 * Lowercase a-z entries of 2-12 letters, minus every entry that IS a charged term, sorted and deduped.
 * `chargedTerms`, never `chargedWords` alone: that list is 21 singular base forms and this filter is
 * exact-token, so on it alone every inflection escapes whole. Matching is whole-token, so SCUNTHORPE lives.
 */
export const deriveWords = (entries: string[]): string[] => {
  const charged = new Set([...chargedTerms].map((term) => term.toLowerCase()))
  const kept = entries.filter(
    (entry) =>
      ENTRY_PATTERN.test(entry) && entry.length >= MIN_LENGTH && entry.length <= MAX_LENGTH && !charged.has(entry),
  )
  return [...new Set(kept)].sort()
}

export const assertEntryFloor = (words: string[]): void => {
  if (words.length < MIN_ENTRIES) {
    throw new Error(`Derived ${words.length} entries, below the ${MIN_ENTRIES} floor`)
  }
}

/** `.prettierignore` carries this directory, so lint cannot reformat the output `--check` compares against. */
export const renderModule = (words: string[]): string =>
  [
    '// GENERATED by scripts/build-cryptic-words.ts from scripts/data/enable.txt -- do not edit by hand.',
    '// Source: ENABLE, public domain; license at scripts/data/LICENSE-enable; digest pinned at',
    '// scripts/data/enable.sha256. Regenerate with `npm run build-cryptic-words`; CI re-derives with',
    '// `--check` on every push.',
    '//',
    '// Every ENABLE entry of 2-12 lowercase letters, minus every entry that IS a charged term. It',
    '// answers ONE question -- is this fodder token a word -- and it is imported by',
    '// src/generators/crypticclue/generator.ts and by nothing else, so nothing lexical is reachable',
    '// from GetPackByDateFunction.',
    'export const knownWords: string[] = [',
    ...words.map((word) => `  '${word}',`),
    ']',
    '',
  ].join('\n')

/** Derive, assert the floor, then write the module or compare it to what is committed. Returns the count. */
export const buildCrypticWords = (check: boolean): number => {
  const words = deriveWords(readSource())
  assertEntryFloor(words)

  const rendered = renderModule(words)
  if (check) {
    const committed = readFileSync(OUTPUT_PATH, 'utf8')
    if (committed !== rendered) {
      throw new Error(
        `${OUTPUT_PATH} is not what scripts/build-cryptic-words.ts derives from scripts/data/enable.txt. Run \`npm run build-cryptic-words\` and commit the result.`,
      )
    }
    return words.length
  }

  writeFileSync(OUTPUT_PATH, rendered, 'utf8')
  return words.length
}

if (require.main === module) {
  // Exit non-zero here rather than inside the body, so every exported function above propagates instead.
  try {
    const check = process.argv.includes('--check')
    const count = buildCrypticWords(check)
    console.log(check ? 'cryptic word list matches the committed file' : `wrote ${OUTPUT_PATH}`)
    console.log(`${count} entries`)
  } catch (error: unknown) {
    console.error('Could not build the cryptic word list', error)
    process.exit(1)
  }
}
